packages:
  - packages/*

catalog:
  '@ianvs/prettier-plugin-sort-imports': ^4.4.1
  '@tailwindcss/vite': ^4.1.3
  '@types/node': ^20.17.30
  '@types/react': ^18.3.1
  '@types/react-dom': ^18.3.1
  '@vitejs/plugin-react-swc': ^3.8.1
  dotenv-cli: ^7.4.2
  prettier: ^3.5.3
  react-dom: ^18.3.1
  react: ^18.3.1
  tailwindcss: ^4.1.3
  typescript: ^5.8.2
  vite-tsconfig-paths: ^5.1.4
  vite: ^5.4.17

verifyDepsBeforeRun: install # replaces stale-dep

# To reduce the risk of installing compromised packages.
# https://pnpm.io/supply-chain-security
minimumReleaseAge: 10080 # 1 week

# https://pnpm.io/settings#sideeffectscache
# sideEffectsCache: false # disable global cache, test postinstall scripts

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
