packages:
  - packages/*
catalog:
  "@ianvs/prettier-plugin-sort-imports": ^4.4.1
  "@tailwindcss/vite": ^4.1.3
  "@types/react": ^18.3.1
  "@types/react-dom": ^18.3.1
  "@vitejs/plugin-react-swc": ^3.8.1
  prettier: ^3.5.3
  react: ^18.3.1
  react-dom: ^18.3.1
  tailwindcss: ^4.1.3
  typescript: ^5.8.2
  vite: ^5.4.17
  vite-tsconfig-paths: ^5.1.4
