packages:
  - 'packages/*'

catalog:
  '@types/react-dom': ^18.3.1
  '@types/react': ^18.3.1
  '@vitejs/plugin-react-swc': ^3.8.1
  'react-dom': ^18.3.1
  'react': ^18.3.1
  'typescript': ^5.8.2
  'vite-tsconfig-paths': ^5.1.4
  'vite': ^5.4.17
